# 01_numpy_02

# ndrary의 shape 조절 함수에 대해 알아보았다.
* `reshape()`: 원하는 형태 (shape)으로 ndarray의 shape을 조절
* `rave()`: 1차원 vector (1차원 ndarray)로 shape을 변형
    * 둘 다 view만 바꿈
* `resize()`: `reshape()`과 상당히 유사

## 1. `reshape()` 함수
> ndarray는 shape을 가지고 있다. <br>
 shape 속성의 값을 바꾸어서 ndarray의 형태를 변경하는 것은 그다지 좋지 않다.<br>
 대신, reshape() 함수를 사용한다.

In [2]:
# ndarray는 shape을 가지고 있다.
# shape 속성의 값을 바꾸어서 ndarray의 형태를 변경하는 것은 그다지 좋지 않다.
# 대신, reshape() 함수를 이용해서 처리를 한다.

import numpy as np

# 1) View
arr = np.arange(0, 12, 1)
print(arr)                # [ 0  1  2  3  4  5  6  7  8  9 10 11]

arr1 = arr.reshape(4, 3)  # 새로운 ndarray를 만드는게 아니라, View를 생성.
print(arr1)               # [[ 0  1  2]
                          #  [ 3  4  5]
                          #  [ 6  7  8]
                          #  [ 9 10 11]]

arr[0] = 100
# View를 통해 데이터를 공유하기 때문에, View의 데이터값도 변한다!!
print(arr)                 # [100   1   2   3   4   5   6   7   8   9  10  11]
print(arr1)                # [[100   1   2]
                           #  [  3   4   5] 
                           #  [  6   7   8]
                           #  [  9  10  11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [3]:
# 2) -1로 인자 자동 설정
arr = np.arange(0, 12, 1)
print(arr)                

arr1 = arr.reshape(2, -1)      # 앞의 값만 2로 결정하면 뒤의 값도 결정된다. 
                               # -1은, 음수값을 넣는게 아니라 자동으로 결정하라는 뜻
print(arr1)                    # [[ 0  1  2  3  4  5]
                               #  [ 6  7  8  9 10 11]]
    
arr1 = arr.reshape(-1, 4)
print(arr1)                    # [[ 0  1  2  3]
                               #  [ 4  5  6  7]
                               #  [ 8  9 10 11]]

arr1 = arr.reshape(2, 2, -1)
print(arr1)                     # [[[ 0  1  2]
                                #   [ 3  4  5]]

                                #  [[ 6  7  8]
                                #   [ 9 10 11]]]                       

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [4]:
# 3) copy()
arr = np.arange(0, 12, 1)
print(arr)                

arr1 = arr.reshape(2, 6).copy()    # View가 아닌, 진짜 shape을 바꾼 ndarray를 만들 때
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## 2. ```ravel()``` 함수

>  ndarray의 모든 요소가 포함된 1차원 vector의 View를 리턴.

In [7]:
## ndrray의 shape 조절 함수
# reshape()을 이용해서 shape를 조절할 수 있다.

# ravel() : ndarray의 모든 요소가 포함된 1차원 vector를 리턴.
#         - View를 리턴한다.

arr = np.arange(0, 10, 1).reshape(5, -1).copy()  # 5 x 20
print(arr)      # [[0 1]
                #  [2 3]
                #  [4 5]
                #  [6 7]
                #  [8 9]]

arr1 = arr.ravel()
print(arr1)    # [0 1 2 3 4 5 6 7 8 9]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


# 9월 7일 (월요일)

## Numpy 2번째 시간

## 3. `resize()`

In [11]:
import numpy as np

# 정수 형태의 난수를 이용해서 (3, 4) shape을 가지는 ndarray를 생성
np.random.seed(10)
arr = np.random.randint(0, 10, (3, 4)) # 0 <= x < 10
print(arr)

# result = arr.resize(2, 6)           # resize()는 스스로 바뀌고 return 값이 없다
# print(result)   # None

arr.resize(2, 6)                     # View가 생성되지않고 원본이 바뀐다.
print(arr)

[[9 4 0 1]
 [9 0 1 8]
 [9 0 8 6]]
[[9 4 0 1 9 0]
 [1 8 9 0 8 6]]


In [14]:
arr.resize(3, 5)   # reshape()은 요소가 갯수가 맞지 않으면 x
                   # resize()는 요소의 갯수가 맞지 않아도 shape이 변경된다.
print(arr)         # 요소 수가 늘어나면 모자란 부분은 0으로 세팅

arr.resize(2, 2)   # 요소 수가 줄어들면 기존 데이터를 버린다.
print(arr)

arr.resize(2, 6)
print(arr)

[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 0 0 0]]
[[9 4]
 [0 1]]
[[9 4 0 1 0 0]
 [0 0 0 0 0 0]]


### 여기까지가 Numpy array (ndarray)의 기본적인 특징


# Indexing & Slicing
* Python의 list할 때도 indexing과 slicing에 대해서 알아보았다.

## 1. 1차원 ndarray

In [15]:
import numpy as np

arr = np.arange(10, 20, 1)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [16]:
# ndarray의 각 요소를 출력하려면 어떻게 해야 할까?
for tmp in arr:
    print(tmp)

10
11
12
13
14
15
16
17
18
19


### `enumerate()` 함수

In [17]:
# enumerate() 함수
for (idx, tmp) in enumerate(arr):
    print("idx : {}, data : {}".format(idx, tmp))

idx : 0, data : 10
idx : 1, data : 11
idx : 2, data : 12
idx : 3, data : 13
idx : 4, data : 14
idx : 5, data : 15
idx : 6, data : 16
idx : 7, data : 17
idx : 8, data : 18
idx : 9, data : 19


In [18]:
arr = np.arange(10, 20, 1)
print(arr[3])      # 13
print(arr[1:4])    # [11 12 13]
print(arr[:-1])    # [10 11 12 13 14 15 16 17 18]
print(arr[1:-1:2]) # [11 13 15 17]   2씩 증가

13
[11 12 13]
[10 11 12 13 14 15 16 17 18]
[11 13 15 17]


## 2. 2차원 ndarray

In [2]:
import numpy as np

arr = np.arange(1, 17, 1).reshape(4, 4).copy()
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [29]:
print(arr[1, 2]) # 7 
print(arr[1])    # [5 6 7 8] : 1행
print(arr[1][2]) # 7

7
[5 6 7 8]
7


In [20]:
print(arr[2, :])    # [ 9 10 11 12] -> 2행

print(arr[1:3, :])  # [[ 5  6  7  8]  -> 1 <= x < 3 행
                    # [ 9 10 11 12]]

print(arr[1:3, :2]) # [[ 5  6]
                    # [ 9 10]]

[6 9 2 4]
[[0 0 1 7]
 [6 9 2 4]]
[[0 0]
 [6 9]]


# Boolean indexing과 Facy indexing

## 1. Boolean Indexing
> Boolean Indexing은, ndarray의 각 요소의 선택여부 
>  - True, False로 구성된 boolean mask를 이용하여 지정하는 방식
>  - boolean mask의 True에 해당하는 index만 조회하는 방식

In [40]:
import numpy as np

np.random.seed(1)
arr = np.random.randint(0, 10, (5, ))
print(arr)               # [5 8 9 5 0]
print(arr % 2)           # [1 0 1 1 0] -> 1차원 vecotr를 scalar로 계산 
                         #  => 1차원으로 브로드캐스팅
    
print(arr % 2 == 0)      # [False  True False False  True] 
                         # -> Boolean Mask : 원본과 shape이 똑같은 T/F ndarray
print(arr[arr % 2 == 0]) # [8 0] => Boolean Indexing

[5 8 9 5 0]
[1 0 1 1 0]
[False  True False False  True]
[8 0]


## 2. Fancy Indexing
> ndarray애 index 배열을 전달하여 배열 요소를 참조하는 방식

## 슬라이싱, 인덱싱, 다중슬라이싱

In [55]:
a = np.arange(0, 12, 1).reshape(3, 4).copy()
print(a)

# 슬라이싱
print(a[0:2])
# [[0 1 2 3]
#  [4 5 6 7]]

# 인덱싱
print(a[1, 2]) # 6

# 다중 슬라이싱
print(a[0:2, 1:2])
# [[1]
#  [5]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
6
[[1]
 [5]]


In [21]:
arr = np.arange(0, 12, 1).reshape(3, 4).copy()
print(arr)

print(arr[2, 2])     # indexing : 10 => Scalar
print(arr[1:2, 2])   # slicing 1행, 2열 -> [6] => 1차원 
print(arr[1:2, 2:3]) # slicing 1행, 2열 -> [[6]] => 2차원 matrix 
print(arr[1:2, 1:3]) # [[5 6]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
[6]
[[6]]


## Fancy Indexing

In [59]:
import numpy as np

a = np.array([10, 11, 12, 13, 14, 15, 16])
index = np.array([1, 4, 5])
print(a[index])  # [11 14 15]

b = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
index = np.array([0, 2])
index2 = np.array([1, 2])
print(b[index, index2]) # [1 8]

print(b[index])
# [[0 1 2]
#  [6 7 8]]

[11 14 15]
[1 8]
[[0 1 2]
 [6 7 8]]


In [61]:
arr = np.arange(0, 12, 1).reshape(3, 4).copy()
print(arr) 
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
print(arr[[0,2], 2])  # [ 2 10]
                      # [0, 2] 0번째행, 2번째 행, 떨어져있는 행 지칭 => 인덱스 배열
                      # [0, 2] 배열의 2열
                      # => [ 2 10]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2 10]


In [62]:
print(arr)
print(arr[[0, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [23]:
print(arr)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

print(arr[[0, 2], 2:3])   # Fancy Indexing에 대한 인덱싱 (2:3) =>  ndarray
# [[ 2]
#  [10]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2]
 [10]]


다음의 ndarray를 추출해 보자 <br>
`[[1 3] 
[9 11]]`
- 행과 열에 동시에 fancy indexing이 적용되지 않는다.

In [74]:
print(arr)
print(arr[[0, 2], [1, 3]]) # [ 1 11] => 행, 열에 둘 다 Fancy Indexing => 엥?
                           # 행과 열에 동시에 fancy indexing이 적용되지 않기 때문! 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1 11]


In [75]:
# 해결방법 1
print(arr)
print(arr[[0,2]][:, [1, 3]]) # 행을 들고 오고, 
                             # :은 인덱싱,열에 다시 fancy indexing 적용

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  3]
 [ 9 11]]


In [76]:
# 해결 2 - Numpy가 함수를 제공한다.
print(arr[np.ix_([0,2], [1,3])])

[[ 1  3]
 [ 9 11]]


# ndarray의 사칙연산과 행렬곱
- 사칙연산 : +, -, *, /
- 행렬곱 : **dot product**
- **Broadcasting**은 사칙연산에서만 일어나고, dot product에서는 일어나지 않는다!

## 1. 행렬 덧셈
- python의 list에서, + 연산자는 concatenation!!
- ndarray에서 + 연산자는 vector, matrix 연산
- ndarray의 사칙연산의 기본 전제는 shape이 같아야 연산이 성립

In [77]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])     # 2 x 3 ndarray
arr2 = np.array([[7, 8, 9], [10, 11, 12]])  # 2 x 3 ndarray
print(arr1)
print(arr2)

print(arr1 + arr2)                          # ndarray의 기본 연산 방식

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]


### 행렬 덧셈의 Broadcasting

In [78]:
arr2 = 3 # scalar는 값을 칭한다.
         # shape이 안맞는 경우, ndarray가 broadcasting을 진행
print(arr1 + arr2)

[[4 5 6]
 [7 8 9]]


In [79]:
arr2 = np.array([1, 2, 3])
# [[1, 2, 3]
#  [1, 2, 3]]  => broadcasting
print(arr1 + arr2)

# arr2 = np.array([1, 2]) --broadcasting X---> [1, 2, 1, 2]

[[2 4 6]
 [5 7 9]]


## 2. 행렬 곱 연산
> 두 행렬간의 행렬곱은 `np.dot()`, `np.matmul()`로 수행이 가능하다.

### `np.dot(A, B)`
> - `np.dot(A, B)`에서 A 행렬의 열 vecotr와, B 행렬의 행 vecotr의 size가 같아야 한다.
> - 만약 크기가 다르다면, `reshape()`이나 `resize()` .. 등으로 크기를 맞춘 후 연산을 수행해야 한다.

In [80]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) 
arr2 = np.array([[7, 8],[9, 10], [11, 12]]) 
print(arr1.shape)          
print(arr2.shape)

print(np.dot(arr1, arr2))   # [[ 58  64]
                            # [139 154]]

(2, 3)
(3, 2)


* *왜 이런 행렬곱 연산을 알아야 하나요?*
 - 만약 행렬곱 연산이 없으면 matrix 연산은 같은 크기로만 연산을 수행해야 한다.
 - 행렬곱 조건만 만족시키면 다양한 크기의 행렬을 우리가 연속적으로 이용해서 특정 작업을 수행할 수 있다
 - 머신러닝, 이미지처리 쪽에서 사용된다.
  - 예) 입력 : 32 x 32 matrix (이미지파일)
  -     출력 : 32 x 10 matrix (다양한 처리가 적용된 이미지)
  -     행렬곱 : (32 x 32) dot (32 x 128) dot (128 x 64) dot (64 x 10)
  -       => 32 x 10

## 3. Transpose 
> 전치행렬
> - 원본행렬의 행은 열로, 열은 행으로 바꾼 행렬을 의미한다.
> - 전치행렬의 표현은 윗첨자로 T를 이용한다.

In [88]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3 ndarray

t_arr = arr.T  # 3 x 2 ndaray

# [[1 2 3]       [[1 4]
# [4 5 6]]  =>   [2 5]
#                [3 6]]
#   2 x 3   ->   3 x 2

print(arr)
print(t_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


원본 행렬의 값을 바꾸면 전치 행렬도 바뀐다.

In [89]:
arr[0][0] = 100
print(arr)
print(t_arr)

[[100   2   3]
 [  4   5   6]]
[[100   4]
 [  2   5]
 [  3   6]]


**벡터**(= 1차원 ndarray) 는 전치행렬이 의미가 없다.

In [91]:
arr  = np.array([1, 2, 3, 4])  # vecotr (1차원 ndarray)
t_arr = arr.T

print(arr)    # [1 2 3 4]
print(t_arr)  # # [1 2 3 4] => 벡터는 전치행렬이 의미가 x

# 하려면 이렇게
t_arr = arr.reshape(4, 1)
print(t_arr)
# [[1]
#  [2]
#  [3]
#  [4]]

[1 2 3 4]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


## 4. Numpy Iterator

> Iterator의 동작 방식과, 왜 쓰는지를 알아야 한다!!
> - Iterator : ndarray의 각 요소를 가르키는 *객체*

### 1) 1차원 -> `c_index`

In [92]:
import numpy as np

# 1차원 ndarray를 만들어서 각 요소 출력
arr = np.array([1, 2, 3, 4, 5])

# for문 이용
for tmp in arr:
    print(tmp, end=' ')
# 1 2 3 4 5 

1 2 3 4 5 

In [95]:
# 이 작업을 iterator를 이용해서 구현
arr = np.array([1, 2, 3, 4, 5])
it = np.nditer(arr, flags=['c_index']) # 1차원인 경우 - index 사용

while not it.finished:    #iterator가 지정하는 위치가 끝이 아닐 동안 반복
    idx = it.index         # iterator가 현재 가리키는 곳의 index 숫자를 가르킨다.
    print(arr[idx], end=' ')
    it.iternext()          # iterator를 다음 요소로 이동시키는 작업
# 1 2 3 4 5 

1 2 3 4 5 

### 2) 2차원 -> `multi_index`

In [97]:
# 2차원 ndarray에 대해서 각 요소를 순서대로 출력하기
# - 0행 0열 -> 0행 1열 -> 0행 2열 -> 1행 0열 -> 1행 1열

arr = np.array([[1, 2, 3], [4, 5, 6]])

for row in range(arr.shape[0]):
    for col in range(arr.shape[1]):
        print(arr[row, col], end= ' ')
# 1 2 3 4 5 6 

1 2 3 4 5 6 

In [ ]:
# 만약 3차원이면 => for문이 3번 돌아야 한다.
# 차원이 높아질 수록 코드 처리가 힘들어진다.

# 이 작업을 iterator를 이용해서 구현
arr = np.array([[1, 2, 3], [4, 5, 6]])
it = np.nditer(arr, flags=['multi_index']) # 다차원에서 사용됨

while not it.finished:    #iterator가 지정하는 위치가 끝이 아닐 동안 반복
    idx = it.multi_index         # iterator가 현재 가리키는 곳의 index 숫자를 가르킨다.
    print(arr[idx], end=' ')
    print(idx)
    it.iternext()          # iterator를 다음 요소로 이동시키는 작업
# 1 (0, 0)
# 2 (0, 1)
# 3 (0, 2)
# 4 (1, 0)
# 5 (1, 1)
# 6 (1, 2)

# ndarray의 비교연산
> 사칙연산과 마찬가지로 비교연산도 같은 index끼리 수행된다.

In [ ]:
np.random.seed(0)
arr1 = np.random.randint(0, 10, (2, 3))
arr2 = np.random.randint(0, 10, (2, 3))
print(arr1)
print(arr2)

print(arr1 == arr2) # Boolean Mask 출력
# [[False False False]
#  [False  True False]]

## `array_equal()`

In [ ]:
# 만약, 2개의 ndarray가 같은 데이터를 가지고 있는지 비교할 때 => array_equal()
arr1 = np.arange(10)
arr2 = np.arange(10)

print(arr1)
print(arr2)
print(np.array_equal(arr1, arr2)) # True

# Numpy 집계함수 & axis(축)

## 집계함수

In [98]:
# 합계

import numpy as np

arr = np.arange(1, 7, 1).reshape(2, 3).copy()
print(arr)

result = 0
for row in range(arr.shape[0]):
    for col in range(arr.shape[1]):
        result += arr[row,col]
        
print(result)         # 21

[[1 2 3]
 [4 5 6]]
21


In [ ]:
print(arr.sum())      # 21

print(np.sum(arr))    # 21

print(np.cumsum(arr)) # 누적합 => [ 1  3  6 10 15 21]
print(np.mean(arr))   # 3.5
print(np.max(arr))    # 6
print(np.min(arr))    # 1

print(np.argmax(arr)) # 최대값의 인덱스/ 순번 => 5
print(np.argmin(arr)) # 최소값의 인덱스/순번 => 0
print(np.std(arr))    # 표준편차 1.707

print(np.exp(arr))    # 자연상수 2.718... (자연로그의 승)
# [[  2.71828183   7.3890561   20.08553692]
#  [ 54.59815003 148.4131591  403.42879349]]

print(np.log10(arr))  # 상용로그값
# [[0.         0.30103    0.47712125]
#  [0.60205999 0.69897    0.77815125]]

이런 집계함수와 수학함수가 제공된다.
* Numpy의 모든 집계함수는 axis를 기준으로 집계된다.
* `np.sum()`
* 만약, axis를 지정하지 않으면 axis는 None으로 설정되고, 함수의 대상 범위를 전체 ndarray로 지정하게 된다.
* 1차원은 축이 1개, 2차원은 축이 2개, 3차원은 축이 3개
    * 이 축 (axis)는 숫자로 표현한다.
* 1차원인 경우 axis = 0 열방향/ 세로방향

## axis를 어떻게 설정하고 어떤 효과가 나타나는지?
> 1차원은 축이 1개, 2차원은 축이 2개, 3차원은 축이 3개

## 1. 1차원
- axis를 지정하지 않으면, 전체 ndarray를 대상으로 `sum()` 수행

In [100]:
arr = np.array([1, 2, 3, 4, 5])		
print(arr)							# [1 2 3 4 5]
print(arr.sum()) 					# 15 
print(arr.sum(axis=0)) 				# 15

[1 2 3 4 5]
15
15


## 2. 2차원
- 2차원 `axis=0` => 행 방향/ 세로 방향 -> ????
- 2차원 `axis=1` => 열 방향/ 가로 방향

In [101]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)                          # [[1 2 3]							
                                    # [4 5 6]]
print(arr.sum())					# 21
print(arr.sum(axis=0))  			# [5 7 9]
print(arr.sum(axis=1))  			# [ 6 15]

print(arr.argmax(axis=0)) 			# [1 1 1]
print(arr.argmax(axis=1)) 			# [2 2]

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
[1 1 1]
[2 2]


## 3. 3차원

In [102]:
np.random.seed(1)
arr1 = np.random.randint(0, 10, (2, 2, 3))
print(arr1)
# [[[5 8 9]
#   [5 0 0]]

#  [[1 7 6]
#   [9 2 4]]]

print(arr1.sum())        # 56

print(arr1.sum(axis=0))  # 3차원에서 axis=0 => depth 방향
# [[ 6 15 15]
#  [14  2  4]]

print(arr1.sum(axis=1))  # 3차원에서 axis=1 => 행 방향/ 세로 방향
# [[10  8  9]
#  [10  9 10]]

print(arr1.sum(axis=2))  # 3차원에서 axis=0 => 열 방향 / 가로 방향
# [[22  5]
#  [14 15]]

[[[5 8 9]
  [5 0 0]]

 [[1 7 6]
  [9 2 4]]]
56
[[ 6 15 15]
 [14  2  4]]
[[10  8  9]
 [10  9 10]]
[[22  5]
 [14 15]]


## Numpy 집계함수를 사용해야 하는 이유
* 집계함수를 사용하는 시간과 로직으로 연산을 수행하는 시간을 비교

In [103]:
import numpy as np

arr = np.arange(100000, dtype=np.float64) 
print(arr)

[0.0000e+00 1.0000e+00 2.0000e+00 ... 9.9997e+04 9.9998e+04 9.9999e+04]


In [104]:
%%time

# for문을 이용해서 합을 구하거나
arr = np.arange(100000, dtype=np.float64) 
result = 0
for tim in arr:
    result += tmp

print(result)
# 500000
# Wall time: 36.9 ms

500000
Wall time: 24.9 ms


In [105]:
%%time

# 집계함수를 이용해서 구할 수 있다.
arr = np.arange(100000, dtype=np.float64) 
print(arr.sum())
# 4999950000.0
# Wall time: 958 µs

4999950000.0
Wall time: 998 µs


## 연습문제

In [106]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4).copy()
print(arr)

# ndarray안에 10보다 큰 수가 몇개 있는지 알아보자
it = np.nditer(arr, flags=['multi_index'])
cnt = 0
while not it.finished:
    idx = it.multi_index
    if arr[idx] > 10:
        cnt += 1
    it.iternext()
it = np.nditer(arr, flags=['multi_index']) 
print(cnt)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
6


In [113]:
# 가장 쉬운 방법은, for문과 if문을 이용한 로직 처리

# boolean mask 이용
arr = np.arange(1, 17).reshape(4, 4).copy()
print((arr > 10).sum())  # 6

print(arr>10) # True만 1이니 sum()을 하면 갯수가 나온다.
# [[False False False False]
#  [False False False False]
#  [False False  True  True]
#  [ True  True  True  True]]

print(arr[arr>10])
# [11 12 13 14 15 16]

6
[[False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[11 12 13 14 15 16]


# ndarray 정렬
> * Numpy array는 axis를 기준으로 정렬하는 `sort()` 함수 제공
> * 만약, axis를 지정하지 않으면 -1값으로 지정 => 마지막 axis
> * np.sort() : 원본은 변하지 않고, 정렬된 결과 ndarray를 리턴
> * arr.sort() : 원본을 정렬, return은 None

## 1) 1차원 ndarray 정렬

In [119]:
import numpy as np

arr = np.arange(10)
np.random.shuffle(arr)

print(np.sort(arr))   # 오름차순 정렬 (default)

# ndarray는 특수한 indexing 제공 => 역순으로 정렬하기 위한 index
print(np.sort(arr)[::1]) # 한칸씩 움직이기 
# [0 1 2 3 4 5 6 7 8 9]

print(np.sort(arr)[::2])
# [0 2 4 6 8]

print(np.sort(arr)[::-1]) # 역 정렬
# [9 8 7 6 5 4 3 2 1 0]

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


## 2) 2차원 ndarray 정렬

In [126]:
arr = np.arange(1, 17)
np.random.shuffle(arr)
arr = arr.reshape(4, 4).copy()
print(arr)
# [[11  2  1 12]
#  [13 10 15  4]
#  [ 9  8 14  3]
#  [16  6  5  7]]


# 2차원 axis=0 => 행/세로방향
print(np.sort(arr, axis=0))
# [[ 9  2  1  3]
#  [11  6  5  4]
#  [13  8 14  7]
#  [16 10 15 12]]

# 2차원 axis=1 => 열/가로방향
print(np.sort(arr, axis=1))
# [[ 1  2 11 12]
#  [ 4 10 13 15]
#  [ 3  8  9 14]
#  [ 5  6  7 16]]

[[11  2  1 12]
 [13 10 15  4]
 [ 9  8 14  3]
 [16  6  5  7]]
[[ 9  2  1  3]
 [11  6  5  4]
 [13  8 14  7]
 [16 10 15 12]]
[[ 1  2 11 12]
 [ 4 10 13 15]
 [ 3  8  9 14]
 [ 5  6  7 16]]


## 연습문제
> 표준정규분포에서 200개의 샘플을 추출한 후, 내림차순으로 상위 5%까지의 결과만 출력

In [127]:
import numpy as np

arr = np.random.randn(200)
print(np.sort(arr)[::-1][1:11]) # 이게 맞나

[2.46162831 2.38520581 2.2968661  2.21191487 1.97969053 1.76939854
 1.76760095 1.73907303 1.73738467 1.68849705]


# ndarray의 원소 추가와 삭제

## 1) `concatenate()` 
> 원소 추가 
> - ndarray에 row(s) 혹은 column(s)을 추가 하기 위한 함수
> - `result = np.concatenate(어떤것을 서로 붙일지, 행으로 붙일지 열로 붙일지)`
    > - `axis=0`: 행방향/ 가로방향
- Python list의 원소 추가 : `append()`
- ndarray의 원소 추가
    - `append()`가 있긴 하지만 잘 쓰진 않는다.
    - `concatenate()`를 더 많이 쓴다.
    
### 하나의 ndarray와 다른 ndarray 연결
- arr에 new_row vector를 하단에 붙인다.
- 결과적으로 3 x 3 matrix 생성

In [128]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3 ndarray
new_row = np.array([7, 8, 9])

# arr에 new_row vector를 하단에 붙인다.
# 결과적으로 3 x 3 matrix 생성

result = np.concatenate((arr, new_row.reshape(1, 3)), axis=0)
print(result)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2) `delete()`
> - axis를 기준으로 행과 열을 삭제
> - 만약 axis를 지정하지 않으면 1차원 배열로 변환 후 삭제
> - 원본을 변경하지 않고 처리가 된 새 배열을 return

### axis를 지정하지 않으면, 1차원 배열로 자동변경된 후 인덱스 삭제

In [129]:
import numpy as np

np.random.seed(1)
arr = np.random.randint(0, 10, (3, 4))
print(arr)

result = np.delete(arr, 1) # axis가 설정되지 않았기 때문에
                           # 1차원 배열로 자동 변경된 후 인덱스를 삭제
print(result)
# [5 8 9 5 0 0 1 7 6 9 2 4]
# [5 9 5 0 0 1 7 6 9 2 4]

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[5 9 5 0 0 1 7 6 9 2 4]


### `axis=0`=> 행 번호, `axis=1` => 열 번호 삭제

In [130]:
np.random.seed(1)

arr = np.random.randint(0, 10, (3, 4))
print(arr)
# [[5 8 9 5]
#  [0 0 1 7]
#  [6 9 2 4]]

result = np.delete(arr, 1, axis=0) # 행번호 1번 삭제           
print(result)
# [[5 8 9 5]
#  [6 9 2 4]]

result = np.delete(arr, 1, axis=1) # 열번호 1번 삭제           
print(result)
# [[5 9 5]
#  [0 1 7]
#  [6 2 4]]

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8 9 5]
 [6 9 2 4]]
[[5 9 5]
 [0 1 7]
 [6 2 4]]


# 연습문제


In [14]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3 ndarray
new_row = np.array([7, 8, 9])

# arra에 new_row vector를 하단에 붙인다.
# 결과적으로 3 x 3 matrix 생성

# result = np.concatenate(어떤것을 서로 붙일지, 행으로 붙일지 열로 붙일지)
result = np.concatenate((arr, new_row.reshape(1, 3)), axis=0)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# `delete()`
> - axis를 기준으로 행과 열을 삭제
> - 만약 axis를 지정하지 않으면 1차원 배열로 변환 후 삭제
> - 원본을 변경하지 않고 처리가 된 새 배열을 return

## axis를 지정하지 않으면, 1차원 배열로 자동변경된 후 인덱스 삭제

In [17]:
import numpy as np

np.random.seed(1)

arr = np.random.randint(0, 10, (3, 4))
print(arr)

result = np.delete(arr, 1) # axis가 설정되지 않았기 때문에
                           # 1차원 배열로 자동 변경된 후 인덱스를 삭제
print(result)
# [5 8 9 5 0 0 1 7 6 9 2 4]
# [5 9 5 0 0 1 7 6 9 2 4]

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[5 9 5 0 0 1 7 6 9 2 4]


## `axis=0`=> 행 번호, `axis=1` => 열 번호 삭제

In [19]:
np.random.seed(1)

arr = np.random.randint(0, 10, (3, 4))
print(arr)
# [[5 8 9 5]
#  [0 0 1 7]
#  [6 9 2 4]]

result = np.delete(arr, 1, axis=0) # 행번호 1번 삭제           
print(result)
# [[5 8 9 5]
#  [6 9 2 4]]

result = np.delete(arr, 1, axis=1) # 열번호 1번 삭제           
print(result)
# [[5 9 5]
#  [0 1 7]
#  [6 2 4]]

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8 9 5]
 [6 9 2 4]]
[[5 9 5]
 [0 1 7]
 [6 2 4]]
